import NextAuthProvider from "@/provider/NextAuthProvider";
import ReactQueryProvider from "@/provider/ReactQueryProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import { Footer } from "@/components/Footer";
import Header from "@/components/Header";
import NuqsProvider from "@/provider/NuqsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Homigo | Accommodation App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <NuqsProvider>
            <NextAuthProvider>
              <Header />
              <Suspense fallback={<Loading />}>
                <div className="min-h-screen">
                  {children}
                  <Toaster />
                </div>
              </Suspense>
              <Footer />
            </NextAuthProvider>
          </NuqsProvider>
        </ReactQueryProvider>
        <Toaster position="top-right" duration={2000} />
      </body>
    </html>
  );
}
